package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * BuildingMaster generated by hbm2java
 */
public class BuildingMaster  implements java.io.Serializable {


     private Integer buildingId;
     private String buildingName;
     private int registrationNo;
     private String address;
     private int contactNo;
     private int floor;
     private int plotNo;
     private int templeId;
     private int campusId;
     private int makerId;
     private int isDeleted;
     private Date systemDatetime;
     private Date DRecordStartdate;
     private Date DRecordEnddate;

    public BuildingMaster() {
    }

    public BuildingMaster(String buildingName, int registrationNo, String address, int contactNo, int floor, int plotNo, int templeId, int campusId, int makerId, int isDeleted, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate) {
       this.buildingName = buildingName;
       this.registrationNo = registrationNo;
       this.address = address;
       this.contactNo = contactNo;
       this.floor = floor;
       this.plotNo = plotNo;
       this.templeId = templeId;
       this.campusId = campusId;
       this.makerId = makerId;
       this.isDeleted = isDeleted;
       this.systemDatetime = systemDatetime;
       this.DRecordStartdate = DRecordStartdate;
       this.DRecordEnddate = DRecordEnddate;
    }
   
    public Integer getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    public int getRegistrationNo() {
        return this.registrationNo;
    }
    
    public void setRegistrationNo(int registrationNo) {
        this.registrationNo = registrationNo;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(int contactNo) {
        this.contactNo = contactNo;
    }
    public int getFloor() {
        return this.floor;
    }
    
    public void setFloor(int floor) {
        this.floor = floor;
    }
    public int getPlotNo() {
        return this.plotNo;
    }
    
    public void setPlotNo(int plotNo) {
        this.plotNo = plotNo;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public int getCampusId() {
        return this.campusId;
    }
    
    public void setCampusId(int campusId) {
        this.campusId = campusId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartdate() {
        return this.DRecordStartdate;
    }
    
    public void setDRecordStartdate(Date DRecordStartdate) {
        this.DRecordStartdate = DRecordStartdate;
    }
    public Date getDRecordEnddate() {
        return this.DRecordEnddate;
    }
    
    public void setDRecordEnddate(Date DRecordEnddate) {
        this.DRecordEnddate = DRecordEnddate;
    }




}


