package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CampusMaster generated by hbm2java
 */
public class CampusMaster  implements java.io.Serializable {


     private Integer campusId;
     private int templeMasterId;
     private String campusName;
     private int plotNo;
     private String registerNo;
     private int noOfBuilding;
     private int isDeleted;
     private int makerId;
     private Date systemDatetime;

    public CampusMaster() {
    }

    public CampusMaster(int templeMasterId, String campusName, int plotNo, String registerNo, int noOfBuilding, int isDeleted, int makerId, Date systemDatetime) {
       this.templeMasterId = templeMasterId;
       this.campusName = campusName;
       this.plotNo = plotNo;
       this.registerNo = registerNo;
       this.noOfBuilding = noOfBuilding;
       this.isDeleted = isDeleted;
       this.makerId = makerId;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getCampusId() {
        return this.campusId;
    }
    
    public void setCampusId(Integer campusId) {
        this.campusId = campusId;
    }
    public int getTempleMasterId() {
        return this.templeMasterId;
    }
    
    public void setTempleMasterId(int templeMasterId) {
        this.templeMasterId = templeMasterId;
    }
    public String getCampusName() {
        return this.campusName;
    }
    
    public void setCampusName(String campusName) {
        this.campusName = campusName;
    }
    public int getPlotNo() {
        return this.plotNo;
    }
    
    public void setPlotNo(int plotNo) {
        this.plotNo = plotNo;
    }
    public String getRegisterNo() {
        return this.registerNo;
    }
    
    public void setRegisterNo(String registerNo) {
        this.registerNo = registerNo;
    }
    public int getNoOfBuilding() {
        return this.noOfBuilding;
    }
    
    public void setNoOfBuilding(int noOfBuilding) {
        this.noOfBuilding = noOfBuilding;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


