package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * CityMaster generated by hbm2java
 */
public class CityMaster  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private int cityCode;
     private int stateId;

    public CityMaster() {
    }

    public CityMaster(String cityName, int cityCode, int stateId) {
       this.cityName = cityName;
       this.cityCode = cityCode;
       this.stateId = stateId;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public int getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(int cityCode) {
        this.cityCode = cityCode;
    }
    public int getStateId() {
        return this.stateId;
    }
    
    public void setStateId(int stateId) {
        this.stateId = stateId;
    }




}


