package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ConsumptionMaster generated by hbm2java
 */
public class ConsumptionMaster  implements java.io.Serializable {


     private Integer consumptionId;
     private String consumptionName;
     private String consumptionDescription;
     private int templeId;
     private int makerId;
     private Date systemDatetime;
     private Date DRecordStartdate;
     private Date DRecordEnddate;

    public ConsumptionMaster() {
    }

    public ConsumptionMaster(String consumptionName, String consumptionDescription, int templeId, int makerId, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate) {
       this.consumptionName = consumptionName;
       this.consumptionDescription = consumptionDescription;
       this.templeId = templeId;
       this.makerId = makerId;
       this.systemDatetime = systemDatetime;
       this.DRecordStartdate = DRecordStartdate;
       this.DRecordEnddate = DRecordEnddate;
    }
   
    public Integer getConsumptionId() {
        return this.consumptionId;
    }
    
    public void setConsumptionId(Integer consumptionId) {
        this.consumptionId = consumptionId;
    }
    public String getConsumptionName() {
        return this.consumptionName;
    }
    
    public void setConsumptionName(String consumptionName) {
        this.consumptionName = consumptionName;
    }
    public String getConsumptionDescription() {
        return this.consumptionDescription;
    }
    
    public void setConsumptionDescription(String consumptionDescription) {
        this.consumptionDescription = consumptionDescription;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartdate() {
        return this.DRecordStartdate;
    }
    
    public void setDRecordStartdate(Date DRecordStartdate) {
        this.DRecordStartdate = DRecordStartdate;
    }
    public Date getDRecordEnddate() {
        return this.DRecordEnddate;
    }
    
    public void setDRecordEnddate(Date DRecordEnddate) {
        this.DRecordEnddate = DRecordEnddate;
    }




}


