package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ConsumptionMinimumStockInfo generated by hbm2java
 */
public class ConsumptionMinimumStockInfo  implements java.io.Serializable {


     private Integer consumptionMinStockId;
     private int consumptionId;
     private int minimumQuantity;
     private int unitId;
     private int availableQuantity;
     private Date systemDatetime;
     private Date DRecordStartdate;
     private Date DRecordEnddate;

    public ConsumptionMinimumStockInfo() {
    }

    public ConsumptionMinimumStockInfo(int consumptionId, int minimumQuantity, int unitId, int availableQuantity, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate) {
       this.consumptionId = consumptionId;
       this.minimumQuantity = minimumQuantity;
       this.unitId = unitId;
       this.availableQuantity = availableQuantity;
       this.systemDatetime = systemDatetime;
       this.DRecordStartdate = DRecordStartdate;
       this.DRecordEnddate = DRecordEnddate;
    }
   
    public Integer getConsumptionMinStockId() {
        return this.consumptionMinStockId;
    }
    
    public void setConsumptionMinStockId(Integer consumptionMinStockId) {
        this.consumptionMinStockId = consumptionMinStockId;
    }
    public int getConsumptionId() {
        return this.consumptionId;
    }
    
    public void setConsumptionId(int consumptionId) {
        this.consumptionId = consumptionId;
    }
    public int getMinimumQuantity() {
        return this.minimumQuantity;
    }
    
    public void setMinimumQuantity(int minimumQuantity) {
        this.minimumQuantity = minimumQuantity;
    }
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
    public int getAvailableQuantity() {
        return this.availableQuantity;
    }
    
    public void setAvailableQuantity(int availableQuantity) {
        this.availableQuantity = availableQuantity;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartdate() {
        return this.DRecordStartdate;
    }
    
    public void setDRecordStartdate(Date DRecordStartdate) {
        this.DRecordStartdate = DRecordStartdate;
    }
    public Date getDRecordEnddate() {
        return this.DRecordEnddate;
    }
    
    public void setDRecordEnddate(Date DRecordEnddate) {
        this.DRecordEnddate = DRecordEnddate;
    }




}


