package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * CountryMaster generated by hbm2java
 */
public class CountryMaster  implements java.io.Serializable {


     private Integer countryId;
     private String countryName;
     private int countryCode;

    public CountryMaster() {
    }

    public CountryMaster(String countryName, int countryCode) {
       this.countryName = countryName;
       this.countryCode = countryCode;
    }
   
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public int getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(int countryCode) {
        this.countryCode = countryCode;
    }




}


