package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DonationBook generated by hbm2java
 */
public class DonationBook  implements java.io.Serializable {


     private Integer donationBookId;
     private int makerId;
     private int donationBookTypeId;
     private int donationBookNumber;
     private String nomination;
     private int noOfReceipt;
     private int totalRupees;
     private int templeId;
     private int isDeleted;
     private Date systemDatetime;

    public DonationBook() {
    }

    public DonationBook(int makerId, int donationBookTypeId, int donationBookNumber, String nomination, int noOfReceipt, int totalRupees, int templeId, int isDeleted, Date systemDatetime) {
       this.makerId = makerId;
       this.donationBookTypeId = donationBookTypeId;
       this.donationBookNumber = donationBookNumber;
       this.nomination = nomination;
       this.noOfReceipt = noOfReceipt;
       this.totalRupees = totalRupees;
       this.templeId = templeId;
       this.isDeleted = isDeleted;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getDonationBookId() {
        return this.donationBookId;
    }
    
    public void setDonationBookId(Integer donationBookId) {
        this.donationBookId = donationBookId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public int getDonationBookTypeId() {
        return this.donationBookTypeId;
    }
    
    public void setDonationBookTypeId(int donationBookTypeId) {
        this.donationBookTypeId = donationBookTypeId;
    }
    public int getDonationBookNumber() {
        return this.donationBookNumber;
    }
    
    public void setDonationBookNumber(int donationBookNumber) {
        this.donationBookNumber = donationBookNumber;
    }
    public String getNomination() {
        return this.nomination;
    }
    
    public void setNomination(String nomination) {
        this.nomination = nomination;
    }
    public int getNoOfReceipt() {
        return this.noOfReceipt;
    }
    
    public void setNoOfReceipt(int noOfReceipt) {
        this.noOfReceipt = noOfReceipt;
    }
    public int getTotalRupees() {
        return this.totalRupees;
    }
    
    public void setTotalRupees(int totalRupees) {
        this.totalRupees = totalRupees;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


