package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DonationBookType generated by hbm2java
 */
public class DonationBookType  implements java.io.Serializable {


     private Integer donationBookTypeId;
     private String donationBookTypeName;
     private String nomination;
     private int noOfReceipt;
     private int templeId;
     private int makerId;
     private int isDeleted;
     private Date systemDatetime;

    public DonationBookType() {
    }

    public DonationBookType(String donationBookTypeName, String nomination, int noOfReceipt, int templeId, int makerId, int isDeleted, Date systemDatetime) {
       this.donationBookTypeName = donationBookTypeName;
       this.nomination = nomination;
       this.noOfReceipt = noOfReceipt;
       this.templeId = templeId;
       this.makerId = makerId;
       this.isDeleted = isDeleted;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getDonationBookTypeId() {
        return this.donationBookTypeId;
    }
    
    public void setDonationBookTypeId(Integer donationBookTypeId) {
        this.donationBookTypeId = donationBookTypeId;
    }
    public String getDonationBookTypeName() {
        return this.donationBookTypeName;
    }
    
    public void setDonationBookTypeName(String donationBookTypeName) {
        this.donationBookTypeName = donationBookTypeName;
    }
    public String getNomination() {
        return this.nomination;
    }
    
    public void setNomination(String nomination) {
        this.nomination = nomination;
    }
    public int getNoOfReceipt() {
        return this.noOfReceipt;
    }
    
    public void setNoOfReceipt(int noOfReceipt) {
        this.noOfReceipt = noOfReceipt;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


