package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ElectionManagement generated by hbm2java
 */
public class ElectionManagement  implements java.io.Serializable {


     private Integer electionId;
     private int areaId;
     private int yearId;
     private int userId;
     private Date fromDate;
     private Date toDate;
     private Date systemDatetime;

    public ElectionManagement() {
    }

    public ElectionManagement(int areaId, int yearId, int userId, Date fromDate, Date toDate, Date systemDatetime) {
       this.areaId = areaId;
       this.yearId = yearId;
       this.userId = userId;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getElectionId() {
        return this.electionId;
    }
    
    public void setElectionId(Integer electionId) {
        this.electionId = electionId;
    }
    public int getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }
    public int getYearId() {
        return this.yearId;
    }
    
    public void setYearId(int yearId) {
        this.yearId = yearId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


