package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * EventMaster generated by hbm2java
 */
public class EventMaster  implements java.io.Serializable {


     private Integer eventId;
     private String eventName;
     private String eventDescription;
     private int templeId;
     private int isDeleted;
     private int makerId;
     private Date systemDatetime;

    public EventMaster() {
    }

    public EventMaster(String eventName, String eventDescription, int templeId, int isDeleted, int makerId, Date systemDatetime) {
       this.eventName = eventName;
       this.eventDescription = eventDescription;
       this.templeId = templeId;
       this.isDeleted = isDeleted;
       this.makerId = makerId;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getEventDescription() {
        return this.eventDescription;
    }
    
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


