package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ExtraItemMaster generated by hbm2java
 */
public class ExtraItemMaster  implements java.io.Serializable {


     private Integer extraItemId;
     private int templeMasterId;
     private String extraItemName;
     private int makerId;
     private int extraItemQty;
     private double extraItemRates;
     private int isDeleted;
     private Date systemDatetime;
     private Date DRecordStartdate;
     private Date DRecordEnddate;

    public ExtraItemMaster() {
    }

    public ExtraItemMaster(int templeMasterId, String extraItemName, int makerId, int extraItemQty, double extraItemRates, int isDeleted, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate) {
       this.templeMasterId = templeMasterId;
       this.extraItemName = extraItemName;
       this.makerId = makerId;
       this.extraItemQty = extraItemQty;
       this.extraItemRates = extraItemRates;
       this.isDeleted = isDeleted;
       this.systemDatetime = systemDatetime;
       this.DRecordStartdate = DRecordStartdate;
       this.DRecordEnddate = DRecordEnddate;
    }
   
    public Integer getExtraItemId() {
        return this.extraItemId;
    }
    
    public void setExtraItemId(Integer extraItemId) {
        this.extraItemId = extraItemId;
    }
    public int getTempleMasterId() {
        return this.templeMasterId;
    }
    
    public void setTempleMasterId(int templeMasterId) {
        this.templeMasterId = templeMasterId;
    }
    public String getExtraItemName() {
        return this.extraItemName;
    }
    
    public void setExtraItemName(String extraItemName) {
        this.extraItemName = extraItemName;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public int getExtraItemQty() {
        return this.extraItemQty;
    }
    
    public void setExtraItemQty(int extraItemQty) {
        this.extraItemQty = extraItemQty;
    }
    public double getExtraItemRates() {
        return this.extraItemRates;
    }
    
    public void setExtraItemRates(double extraItemRates) {
        this.extraItemRates = extraItemRates;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartdate() {
        return this.DRecordStartdate;
    }
    
    public void setDRecordStartdate(Date DRecordStartdate) {
        this.DRecordStartdate = DRecordStartdate;
    }
    public Date getDRecordEnddate() {
        return this.DRecordEnddate;
    }
    
    public void setDRecordEnddate(Date DRecordEnddate) {
        this.DRecordEnddate = DRecordEnddate;
    }




}


