package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * FloorMaster generated by hbm2java
 */
public class FloorMaster  implements java.io.Serializable {


     private Integer floorId;
     private String floorName;
     private int noOfRoom;
     private int buildingId;
     private int isDeleted;

    public FloorMaster() {
    }

    public FloorMaster(String floorName, int noOfRoom, int buildingId, int isDeleted) {
       this.floorName = floorName;
       this.noOfRoom = noOfRoom;
       this.buildingId = buildingId;
       this.isDeleted = isDeleted;
    }
   
    public Integer getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }
    public String getFloorName() {
        return this.floorName;
    }
    
    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }
    public int getNoOfRoom() {
        return this.noOfRoom;
    }
    
    public void setNoOfRoom(int noOfRoom) {
        this.noOfRoom = noOfRoom;
    }
    public int getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(int buildingId) {
        this.buildingId = buildingId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


