package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * FormMaster generated by hbm2java
 */
public class FormMaster  implements java.io.Serializable {


     private Integer formId;
     private String formTitle;
     private String url;
     private int moduleId;
     private int isDeleted;

    public FormMaster() {
    }

    public FormMaster(String formTitle, String url, int moduleId, int isDeleted) {
       this.formTitle = formTitle;
       this.url = url;
       this.moduleId = moduleId;
       this.isDeleted = isDeleted;
    }
   
    public Integer getFormId() {
        return this.formId;
    }
    
    public void setFormId(Integer formId) {
        this.formId = formId;
    }
    public String getFormTitle() {
        return this.formTitle;
    }
    
    public void setFormTitle(String formTitle) {
        this.formTitle = formTitle;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


