package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ItemInfo generated by hbm2java
 */
public class ItemInfo  implements java.io.Serializable {


     private Integer itemId;
     private String itemName;
     private int unitId;
     private int minimumQuantity;
     private int availableItemStock;
     private Date systemDatetime;
     private Date DRecordItemStartdate;
     private Date DRecordItemEnddate;

    public ItemInfo() {
    }

    public ItemInfo(String itemName, int unitId, int minimumQuantity, int availableItemStock, Date systemDatetime, Date DRecordItemStartdate, Date DRecordItemEnddate) {
       this.itemName = itemName;
       this.unitId = unitId;
       this.minimumQuantity = minimumQuantity;
       this.availableItemStock = availableItemStock;
       this.systemDatetime = systemDatetime;
       this.DRecordItemStartdate = DRecordItemStartdate;
       this.DRecordItemEnddate = DRecordItemEnddate;
    }
   
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
    public int getMinimumQuantity() {
        return this.minimumQuantity;
    }
    
    public void setMinimumQuantity(int minimumQuantity) {
        this.minimumQuantity = minimumQuantity;
    }
    public int getAvailableItemStock() {
        return this.availableItemStock;
    }
    
    public void setAvailableItemStock(int availableItemStock) {
        this.availableItemStock = availableItemStock;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordItemStartdate() {
        return this.DRecordItemStartdate;
    }
    
    public void setDRecordItemStartdate(Date DRecordItemStartdate) {
        this.DRecordItemStartdate = DRecordItemStartdate;
    }
    public Date getDRecordItemEnddate() {
        return this.DRecordItemEnddate;
    }
    
    public void setDRecordItemEnddate(Date DRecordItemEnddate) {
        this.DRecordItemEnddate = DRecordItemEnddate;
    }




}


