package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * LoginLog generated by hbm2java
 */
public class LoginLog  implements java.io.Serializable {


     private Integer loginLogId;
     private int userMasterId;
     private int templeId;
     private int roleId;
     private String domain;
     private String ip;
     private Date datetime;

    public LoginLog() {
    }

    public LoginLog(int userMasterId, int templeId, int roleId, String domain, String ip, Date datetime) {
       this.userMasterId = userMasterId;
       this.templeId = templeId;
       this.roleId = roleId;
       this.domain = domain;
       this.ip = ip;
       this.datetime = datetime;
    }
   
    public Integer getLoginLogId() {
        return this.loginLogId;
    }
    
    public void setLoginLogId(Integer loginLogId) {
        this.loginLogId = loginLogId;
    }
    public int getUserMasterId() {
        return this.userMasterId;
    }
    
    public void setUserMasterId(int userMasterId) {
        this.userMasterId = userMasterId;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


