package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * ModuleMaster generated by hbm2java
 */
public class ModuleMaster  implements java.io.Serializable {


     private Integer moduleId;
     private String moduleName;
     private String moduleDescription;
     private byte isDeleted;

    public ModuleMaster() {
    }

    public ModuleMaster(String moduleName, String moduleDescription, byte isDeleted) {
       this.moduleName = moduleName;
       this.moduleDescription = moduleDescription;
       this.isDeleted = isDeleted;
    }
   
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }
    public String getModuleDescription() {
        return this.moduleDescription;
    }
    
    public void setModuleDescription(String moduleDescription) {
        this.moduleDescription = moduleDescription;
    }
    public byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(byte isDeleted) {
        this.isDeleted = isDeleted;
    }




}


