package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * PrasadParameter generated by hbm2java
 */
public class PrasadParameter  implements java.io.Serializable {


     private Integer prasadParameterId;
     private String parameterName;
     private int unitId;

    public PrasadParameter() {
    }

    public PrasadParameter(String parameterName, int unitId) {
       this.parameterName = parameterName;
       this.unitId = unitId;
    }
   
    public Integer getPrasadParameterId() {
        return this.prasadParameterId;
    }
    
    public void setPrasadParameterId(Integer prasadParameterId) {
        this.prasadParameterId = prasadParameterId;
    }
    public String getParameterName() {
        return this.parameterName;
    }
    
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }




}


