package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PrasadMaster generated by hbm2java
 */
public class PrasadMaster  implements java.io.Serializable {


     private Integer prasadId;
     private String prasadName;
     private String prasadDescription;
     private String prasadParameterId;
     private int templeId;
     private int makerId;
     private int isDeleted;
     private Date systemDatetime;

    public PrasadMaster() {
    }

    public PrasadMaster(String prasadName, String prasadDescription, String prasadParameterId, int templeId, int makerId, int isDeleted, Date systemDatetime) {
       this.prasadName = prasadName;
       this.prasadDescription = prasadDescription;
       this.prasadParameterId = prasadParameterId;
       this.templeId = templeId;
       this.makerId = makerId;
       this.isDeleted = isDeleted;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getPrasadId() {
        return this.prasadId;
    }
    
    public void setPrasadId(Integer prasadId) {
        this.prasadId = prasadId;
    }
    public String getPrasadName() {
        return this.prasadName;
    }
    
    public void setPrasadName(String prasadName) {
        this.prasadName = prasadName;
    }
    public String getPrasadDescription() {
        return this.prasadDescription;
    }
    
    public void setPrasadDescription(String prasadDescription) {
        this.prasadDescription = prasadDescription;
    }
    public String getPrasadParameterId() {
        return this.prasadParameterId;
    }
    
    public void setPrasadParameterId(String prasadParameterId) {
        this.prasadParameterId = prasadParameterId;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


