package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PurchaseInvoiceTable generated by hbm2java
 */
public class PurchaseInvoiceTable  implements java.io.Serializable {


     private Integer purchaseId;
     private int itemId;
     private int supplierId;
     private int makerId;
     private int qty;
     private double priceperunit;
     private double totalprize;
     private int unitId;
     private Date systemDatetime;

    public PurchaseInvoiceTable() {
    }

    public PurchaseInvoiceTable(int itemId, int supplierId, int makerId, int qty, double priceperunit, double totalprize, int unitId, Date systemDatetime) {
       this.itemId = itemId;
       this.supplierId = supplierId;
       this.makerId = makerId;
       this.qty = qty;
       this.priceperunit = priceperunit;
       this.totalprize = totalprize;
       this.unitId = unitId;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public int getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public double getPriceperunit() {
        return this.priceperunit;
    }
    
    public void setPriceperunit(double priceperunit) {
        this.priceperunit = priceperunit;
    }
    public double getTotalprize() {
        return this.totalprize;
    }
    
    public void setTotalprize(double totalprize) {
        this.totalprize = totalprize;
    }
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


