package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ReceiptInfo generated by hbm2java
 */
public class ReceiptInfo  implements java.io.Serializable {


     private Integer receiptId;
     private int userMasterId;
     private int accountId;
     private double rupees;
     private int quantity;
     private int unitId;
     private String note;
     private String specialNote;
     private Date systemDatetime;

    public ReceiptInfo() {
    }

    public ReceiptInfo(int userMasterId, int accountId, double rupees, int quantity, int unitId, String note, String specialNote, Date systemDatetime) {
       this.userMasterId = userMasterId;
       this.accountId = accountId;
       this.rupees = rupees;
       this.quantity = quantity;
       this.unitId = unitId;
       this.note = note;
       this.specialNote = specialNote;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(Integer receiptId) {
        this.receiptId = receiptId;
    }
    public int getUserMasterId() {
        return this.userMasterId;
    }
    
    public void setUserMasterId(int userMasterId) {
        this.userMasterId = userMasterId;
    }
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public double getRupees() {
        return this.rupees;
    }
    
    public void setRupees(double rupees) {
        this.rupees = rupees;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getSpecialNote() {
        return this.specialNote;
    }
    
    public void setSpecialNote(String specialNote) {
        this.specialNote = specialNote;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


