package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * RoomTypeMaster generated by hbm2java
 */
public class RoomTypeMaster  implements java.io.Serializable {


     private Integer roomTypeId;
     private String roomTypeName;
     private int templeMasterId;
     private int isDeleted;
     private int makerId;
     private Date sysDataTime;

    public RoomTypeMaster() {
    }

    public RoomTypeMaster(String roomTypeName, int templeMasterId, int isDeleted, int makerId, Date sysDataTime) {
       this.roomTypeName = roomTypeName;
       this.templeMasterId = templeMasterId;
       this.isDeleted = isDeleted;
       this.makerId = makerId;
       this.sysDataTime = sysDataTime;
    }
   
    public Integer getRoomTypeId() {
        return this.roomTypeId;
    }
    
    public void setRoomTypeId(Integer roomTypeId) {
        this.roomTypeId = roomTypeId;
    }
    public String getRoomTypeName() {
        return this.roomTypeName;
    }
    
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName;
    }
    public int getTempleMasterId() {
        return this.templeMasterId;
    }
    
    public void setTempleMasterId(int templeMasterId) {
        this.templeMasterId = templeMasterId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSysDataTime() {
        return this.sysDataTime;
    }
    
    public void setSysDataTime(Date sysDataTime) {
        this.sysDataTime = sysDataTime;
    }




}


