package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * RoomMaster generated by hbm2java
 */
public class RoomMaster  implements java.io.Serializable {


     private Integer roomMasterId;
     private String roomNo;
     private int roomTypeId;
     private double rate;
     private double deposit;
     private int capacity;
     private int maxAllowed;
     private double extraMemberRate;
     private int threshold;
     private int isActive;
     private int floorId;
     private int buildingId;
     private int isDeleted;
     private int makerId;
     private Date systemDatetime;

    public RoomMaster() {
    }

    public RoomMaster(String roomNo, int roomTypeId, double rate, double deposit, int capacity, int maxAllowed, double extraMemberRate, int threshold, int isActive, int floorId, int buildingId, int isDeleted, int makerId, Date systemDatetime) {
       this.roomNo = roomNo;
       this.roomTypeId = roomTypeId;
       this.rate = rate;
       this.deposit = deposit;
       this.capacity = capacity;
       this.maxAllowed = maxAllowed;
       this.extraMemberRate = extraMemberRate;
       this.threshold = threshold;
       this.isActive = isActive;
       this.floorId = floorId;
       this.buildingId = buildingId;
       this.isDeleted = isDeleted;
       this.makerId = makerId;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getRoomMasterId() {
        return this.roomMasterId;
    }
    
    public void setRoomMasterId(Integer roomMasterId) {
        this.roomMasterId = roomMasterId;
    }
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public int getRoomTypeId() {
        return this.roomTypeId;
    }
    
    public void setRoomTypeId(int roomTypeId) {
        this.roomTypeId = roomTypeId;
    }
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }
    public double getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(double deposit) {
        this.deposit = deposit;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public int getMaxAllowed() {
        return this.maxAllowed;
    }
    
    public void setMaxAllowed(int maxAllowed) {
        this.maxAllowed = maxAllowed;
    }
    public double getExtraMemberRate() {
        return this.extraMemberRate;
    }
    
    public void setExtraMemberRate(double extraMemberRate) {
        this.extraMemberRate = extraMemberRate;
    }
    public int getThreshold() {
        return this.threshold;
    }
    
    public void setThreshold(int threshold) {
        this.threshold = threshold;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public int getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(int floorId) {
        this.floorId = floorId;
    }
    public int getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(int buildingId) {
        this.buildingId = buildingId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


