package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * RoomBookingMaster generated by hbm2java
 */
public class RoomBookingMaster  implements java.io.Serializable {


     private Integer roomBookingId;
     private int roomNo;
     private double extraItemRate;
     private double extraMemberRate;
     private double roomRate;
     private double advancePayment;
     private double deposit;
     private double totalAmount;
     private Date checkinDate;
     private Date checkoutDate;
     private int userMasterId;
     private int templeMasterId;
     private int makerId;
     private Date systemDatetime;

    public RoomBookingMaster() {
    }

    public RoomBookingMaster(int roomNo, double extraItemRate, double extraMemberRate, double roomRate, double advancePayment, double deposit, double totalAmount, Date checkinDate, Date checkoutDate, int userMasterId, int templeMasterId, int makerId, Date systemDatetime) {
       this.roomNo = roomNo;
       this.extraItemRate = extraItemRate;
       this.extraMemberRate = extraMemberRate;
       this.roomRate = roomRate;
       this.advancePayment = advancePayment;
       this.deposit = deposit;
       this.totalAmount = totalAmount;
       this.checkinDate = checkinDate;
       this.checkoutDate = checkoutDate;
       this.userMasterId = userMasterId;
       this.templeMasterId = templeMasterId;
       this.makerId = makerId;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getRoomBookingId() {
        return this.roomBookingId;
    }
    
    public void setRoomBookingId(Integer roomBookingId) {
        this.roomBookingId = roomBookingId;
    }
    public int getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(int roomNo) {
        this.roomNo = roomNo;
    }
    public double getExtraItemRate() {
        return this.extraItemRate;
    }
    
    public void setExtraItemRate(double extraItemRate) {
        this.extraItemRate = extraItemRate;
    }
    public double getExtraMemberRate() {
        return this.extraMemberRate;
    }
    
    public void setExtraMemberRate(double extraMemberRate) {
        this.extraMemberRate = extraMemberRate;
    }
    public double getRoomRate() {
        return this.roomRate;
    }
    
    public void setRoomRate(double roomRate) {
        this.roomRate = roomRate;
    }
    public double getAdvancePayment() {
        return this.advancePayment;
    }
    
    public void setAdvancePayment(double advancePayment) {
        this.advancePayment = advancePayment;
    }
    public double getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(double deposit) {
        this.deposit = deposit;
    }
    public double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getCheckinDate() {
        return this.checkinDate;
    }
    
    public void setCheckinDate(Date checkinDate) {
        this.checkinDate = checkinDate;
    }
    public Date getCheckoutDate() {
        return this.checkoutDate;
    }
    
    public void setCheckoutDate(Date checkoutDate) {
        this.checkoutDate = checkoutDate;
    }
    public int getUserMasterId() {
        return this.userMasterId;
    }
    
    public void setUserMasterId(int userMasterId) {
        this.userMasterId = userMasterId;
    }
    public int getTempleMasterId() {
        return this.templeMasterId;
    }
    
    public void setTempleMasterId(int templeMasterId) {
        this.templeMasterId = templeMasterId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


