package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SupplierItemTable generated by hbm2java
 */
public class SupplierItemTable  implements java.io.Serializable {


     private Integer supplierItemId;
     private int supplierId;
     private int itemId;
     private int quantity;
     private int unitId;
     private double totalPrize;
     private double totalTax;
     private double shippingCost;
     private double pricePerUnit;
     private byte isPaid;
     private Date systemDatetime;

    public SupplierItemTable() {
    }

    public SupplierItemTable(int supplierId, int itemId, int quantity, int unitId, double totalPrize, double totalTax, double shippingCost, double pricePerUnit, byte isPaid, Date systemDatetime) {
       this.supplierId = supplierId;
       this.itemId = itemId;
       this.quantity = quantity;
       this.unitId = unitId;
       this.totalPrize = totalPrize;
       this.totalTax = totalTax;
       this.shippingCost = shippingCost;
       this.pricePerUnit = pricePerUnit;
       this.isPaid = isPaid;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getSupplierItemId() {
        return this.supplierItemId;
    }
    
    public void setSupplierItemId(Integer supplierItemId) {
        this.supplierItemId = supplierItemId;
    }
    public int getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
    public double getTotalPrize() {
        return this.totalPrize;
    }
    
    public void setTotalPrize(double totalPrize) {
        this.totalPrize = totalPrize;
    }
    public double getTotalTax() {
        return this.totalTax;
    }
    
    public void setTotalTax(double totalTax) {
        this.totalTax = totalTax;
    }
    public double getShippingCost() {
        return this.shippingCost;
    }
    
    public void setShippingCost(double shippingCost) {
        this.shippingCost = shippingCost;
    }
    public double getPricePerUnit() {
        return this.pricePerUnit;
    }
    
    public void setPricePerUnit(double pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
    }
    public byte getIsPaid() {
        return this.isPaid;
    }
    
    public void setIsPaid(byte isPaid) {
        this.isPaid = isPaid;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


