package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SupplierMaster generated by hbm2java
 */
public class SupplierMaster  implements java.io.Serializable {


     private Integer supplierId;
     private String name;
     private String address;
     private int pincodeNo;
     private double mobileNo;
     private double mobileNo2;
     private int cityId;
     private int stateId;
     private int templeId;
     private String emailId;
     private String facebookId;
     private double faxNo;
     private Date birthdate;
     private String electionCardNo;
     private String adharCardNo;
     private String drivingLicenceNo;
     private String pancardNo;
     private int makerId;
     private Date systemDatetime;
     private Date DRecordStartdate;
     private Date DRecordEnddate;

    public SupplierMaster() {
    }

    public SupplierMaster(String name, String address, int pincodeNo, double mobileNo, double mobileNo2, int cityId, int stateId, int templeId, String emailId, String facebookId, double faxNo, Date birthdate, String electionCardNo, String adharCardNo, String drivingLicenceNo, String pancardNo, int makerId, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate) {
       this.name = name;
       this.address = address;
       this.pincodeNo = pincodeNo;
       this.mobileNo = mobileNo;
       this.mobileNo2 = mobileNo2;
       this.cityId = cityId;
       this.stateId = stateId;
       this.templeId = templeId;
       this.emailId = emailId;
       this.facebookId = facebookId;
       this.faxNo = faxNo;
       this.birthdate = birthdate;
       this.electionCardNo = electionCardNo;
       this.adharCardNo = adharCardNo;
       this.drivingLicenceNo = drivingLicenceNo;
       this.pancardNo = pancardNo;
       this.makerId = makerId;
       this.systemDatetime = systemDatetime;
       this.DRecordStartdate = DRecordStartdate;
       this.DRecordEnddate = DRecordEnddate;
    }
   
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getPincodeNo() {
        return this.pincodeNo;
    }
    
    public void setPincodeNo(int pincodeNo) {
        this.pincodeNo = pincodeNo;
    }
    public double getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(double mobileNo) {
        this.mobileNo = mobileNo;
    }
    public double getMobileNo2() {
        return this.mobileNo2;
    }
    
    public void setMobileNo2(double mobileNo2) {
        this.mobileNo2 = mobileNo2;
    }
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public int getStateId() {
        return this.stateId;
    }
    
    public void setStateId(int stateId) {
        this.stateId = stateId;
    }
    public int getTempleId() {
        return this.templeId;
    }
    
    public void setTempleId(int templeId) {
        this.templeId = templeId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }
    public double getFaxNo() {
        return this.faxNo;
    }
    
    public void setFaxNo(double faxNo) {
        this.faxNo = faxNo;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getElectionCardNo() {
        return this.electionCardNo;
    }
    
    public void setElectionCardNo(String electionCardNo) {
        this.electionCardNo = electionCardNo;
    }
    public String getAdharCardNo() {
        return this.adharCardNo;
    }
    
    public void setAdharCardNo(String adharCardNo) {
        this.adharCardNo = adharCardNo;
    }
    public String getDrivingLicenceNo() {
        return this.drivingLicenceNo;
    }
    
    public void setDrivingLicenceNo(String drivingLicenceNo) {
        this.drivingLicenceNo = drivingLicenceNo;
    }
    public String getPancardNo() {
        return this.pancardNo;
    }
    
    public void setPancardNo(String pancardNo) {
        this.pancardNo = pancardNo;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartdate() {
        return this.DRecordStartdate;
    }
    
    public void setDRecordStartdate(Date DRecordStartdate) {
        this.DRecordStartdate = DRecordStartdate;
    }
    public Date getDRecordEnddate() {
        return this.DRecordEnddate;
    }
    
    public void setDRecordEnddate(Date DRecordEnddate) {
        this.DRecordEnddate = DRecordEnddate;
    }




}


