package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TempleMaster generated by hbm2java
 */
public class TempleMaster  implements java.io.Serializable {


     private Integer templeMasterId;
     private String templeName;
     private String templeRegistrationNo;
     private String address;
     private int stateId;
     private int cityId;
     private String pincode;
     private String landlineNo;
     private double mobileNo;
     private String image;
     private byte isDeleted;
     private int makerId;
     private Date sysDateTime;

    public TempleMaster() {
    }

    public TempleMaster(String templeName, String templeRegistrationNo, String address, int stateId, int cityId, String pincode, String landlineNo, double mobileNo, String image, byte isDeleted, int makerId, Date sysDateTime) {
       this.templeName = templeName;
       this.templeRegistrationNo = templeRegistrationNo;
       this.address = address;
       this.stateId = stateId;
       this.cityId = cityId;
       this.pincode = pincode;
       this.landlineNo = landlineNo;
       this.mobileNo = mobileNo;
       this.image = image;
       this.isDeleted = isDeleted;
       this.makerId = makerId;
       this.sysDateTime = sysDateTime;
    }
   
    public Integer getTempleMasterId() {
        return this.templeMasterId;
    }
    
    public void setTempleMasterId(Integer templeMasterId) {
        this.templeMasterId = templeMasterId;
    }
    public String getTempleName() {
        return this.templeName;
    }
    
    public void setTempleName(String templeName) {
        this.templeName = templeName;
    }
    public String getTempleRegistrationNo() {
        return this.templeRegistrationNo;
    }
    
    public void setTempleRegistrationNo(String templeRegistrationNo) {
        this.templeRegistrationNo = templeRegistrationNo;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getStateId() {
        return this.stateId;
    }
    
    public void setStateId(int stateId) {
        this.stateId = stateId;
    }
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getLandlineNo() {
        return this.landlineNo;
    }
    
    public void setLandlineNo(String landlineNo) {
        this.landlineNo = landlineNo;
    }
    public double getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(double mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public byte getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(byte isDeleted) {
        this.isDeleted = isDeleted;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSysDateTime() {
        return this.sysDateTime;
    }
    
    public void setSysDateTime(Date sysDateTime) {
        this.sysDateTime = sysDateTime;
    }




}


