package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * UnitMaster generated by hbm2java
 */
public class UnitMaster  implements java.io.Serializable {


     private Integer unitId;
     private String unitName;

    public UnitMaster() {
    }

    public UnitMaster(String unitName) {
       this.unitName = unitName;
    }
   
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }




}


