package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0



/**
 * UnitFormula generated by hbm2java
 */
public class UnitFormula  implements java.io.Serializable {


     private Integer unitFormulaId;
     private int unitId1;
     private int unitId2;

    public UnitFormula() {
    }

    public UnitFormula(int unitId1, int unitId2) {
       this.unitId1 = unitId1;
       this.unitId2 = unitId2;
    }
   
    public Integer getUnitFormulaId() {
        return this.unitFormulaId;
    }
    
    public void setUnitFormulaId(Integer unitFormulaId) {
        this.unitFormulaId = unitFormulaId;
    }
    public int getUnitId1() {
        return this.unitId1;
    }
    
    public void setUnitId1(int unitId1) {
        this.unitId1 = unitId1;
    }
    public int getUnitId2() {
        return this.unitId2;
    }
    
    public void setUnitId2(int unitId2) {
        this.unitId2 = unitId2;
    }




}


