package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UsageItemInfo generated by hbm2java
 */
public class UsageItemInfo  implements java.io.Serializable {


     private Integer usageItemInfoId;
     private int consumptionId;
     private int itemId;
     private Date systemDatetime;

    public UsageItemInfo() {
    }

    public UsageItemInfo(int consumptionId, int itemId, Date systemDatetime) {
       this.consumptionId = consumptionId;
       this.itemId = itemId;
       this.systemDatetime = systemDatetime;
    }
   
    public Integer getUsageItemInfoId() {
        return this.usageItemInfoId;
    }
    
    public void setUsageItemInfoId(Integer usageItemInfoId) {
        this.usageItemInfoId = usageItemInfoId;
    }
    public int getConsumptionId() {
        return this.consumptionId;
    }
    
    public void setConsumptionId(int consumptionId) {
        this.consumptionId = consumptionId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }




}


