package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UsageItemStockInfo generated by hbm2java
 */
public class UsageItemStockInfo  implements java.io.Serializable {


     private Integer itemStockId;
     private int usageItemInfoId;
     private int quantity;
     private int unitId;
     private Date systemDatetime;
     private Date DRecordItemStartdate;
     private Date DRecordItemEnddate;

    public UsageItemStockInfo() {
    }

    public UsageItemStockInfo(int usageItemInfoId, int quantity, int unitId, Date systemDatetime, Date DRecordItemStartdate, Date DRecordItemEnddate) {
       this.usageItemInfoId = usageItemInfoId;
       this.quantity = quantity;
       this.unitId = unitId;
       this.systemDatetime = systemDatetime;
       this.DRecordItemStartdate = DRecordItemStartdate;
       this.DRecordItemEnddate = DRecordItemEnddate;
    }
   
    public Integer getItemStockId() {
        return this.itemStockId;
    }
    
    public void setItemStockId(Integer itemStockId) {
        this.itemStockId = itemStockId;
    }
    public int getUsageItemInfoId() {
        return this.usageItemInfoId;
    }
    
    public void setUsageItemInfoId(int usageItemInfoId) {
        this.usageItemInfoId = usageItemInfoId;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordItemStartdate() {
        return this.DRecordItemStartdate;
    }
    
    public void setDRecordItemStartdate(Date DRecordItemStartdate) {
        this.DRecordItemStartdate = DRecordItemStartdate;
    }
    public Date getDRecordItemEnddate() {
        return this.DRecordItemEnddate;
    }
    
    public void setDRecordItemEnddate(Date DRecordItemEnddate) {
        this.DRecordItemEnddate = DRecordItemEnddate;
    }




}


