package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo  implements java.io.Serializable {


     private Integer userInfoId;
     private UserMaster userMaster;
     private String address;
     private int landlineNo;
     private String dob;
     private String facebookId;
     private String electionCardNo;
     private String adharCardNo;
     private String drivingLicenceNo;
     private String pancardNo;
     private int pincode;
     private String image;
     private int isDeleted;
     private Set donationReceiptMasters = new HashSet(0);

    public UserInfo() {
    }

	
    public UserInfo(UserMaster userMaster, String address, int landlineNo, String dob, String facebookId, String electionCardNo, String adharCardNo, String drivingLicenceNo, String pancardNo, int pincode, String image, int isDeleted) {
        this.userMaster = userMaster;
        this.address = address;
        this.landlineNo = landlineNo;
        this.dob = dob;
        this.facebookId = facebookId;
        this.electionCardNo = electionCardNo;
        this.adharCardNo = adharCardNo;
        this.drivingLicenceNo = drivingLicenceNo;
        this.pancardNo = pancardNo;
        this.pincode = pincode;
        this.image = image;
        this.isDeleted = isDeleted;
    }
    public UserInfo(UserMaster userMaster, String address, int landlineNo, String dob, String facebookId, String electionCardNo, String adharCardNo, String drivingLicenceNo, String pancardNo, int pincode, String image, int isDeleted, Set donationReceiptMasters) {
       this.userMaster = userMaster;
       this.address = address;
       this.landlineNo = landlineNo;
       this.dob = dob;
       this.facebookId = facebookId;
       this.electionCardNo = electionCardNo;
       this.adharCardNo = adharCardNo;
       this.drivingLicenceNo = drivingLicenceNo;
       this.pancardNo = pancardNo;
       this.pincode = pincode;
       this.image = image;
       this.isDeleted = isDeleted;
       this.donationReceiptMasters = donationReceiptMasters;
    }
   
    public Integer getUserInfoId() {
        return this.userInfoId;
    }
    
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getLandlineNo() {
        return this.landlineNo;
    }
    
    public void setLandlineNo(int landlineNo) {
        this.landlineNo = landlineNo;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }
    public String getElectionCardNo() {
        return this.electionCardNo;
    }
    
    public void setElectionCardNo(String electionCardNo) {
        this.electionCardNo = electionCardNo;
    }
    public String getAdharCardNo() {
        return this.adharCardNo;
    }
    
    public void setAdharCardNo(String adharCardNo) {
        this.adharCardNo = adharCardNo;
    }
    public String getDrivingLicenceNo() {
        return this.drivingLicenceNo;
    }
    
    public void setDrivingLicenceNo(String drivingLicenceNo) {
        this.drivingLicenceNo = drivingLicenceNo;
    }
    public String getPancardNo() {
        return this.pancardNo;
    }
    
    public void setPancardNo(String pancardNo) {
        this.pancardNo = pancardNo;
    }
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getDonationReceiptMasters() {
        return this.donationReceiptMasters;
    }
    
    public void setDonationReceiptMasters(Set donationReceiptMasters) {
        this.donationReceiptMasters = donationReceiptMasters;
    }




}


