package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserMaster generated by hbm2java
 */
public class UserMaster  implements java.io.Serializable {


     private Integer userMasterId;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String emailid;
     private double mobileNo;
     private int guid;
     private int roleId;
     private int templeMasterId;
     private int makerId;
     private int isDeleted;
     private Date systemDatetime;
     private Date DRecordStartdate;
     private Date DRecordEnddate;
     private Set userInfos = new HashSet(0);
     private Set userAddressInfos = new HashSet(0);

    public UserMaster() {
    }

	
    public UserMaster(String username, String password, String firstName, String lastName, String emailid, double mobileNo, int guid, int roleId, int templeMasterId, int makerId, int isDeleted, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailid = emailid;
        this.mobileNo = mobileNo;
        this.guid = guid;
        this.roleId = roleId;
        this.templeMasterId = templeMasterId;
        this.makerId = makerId;
        this.isDeleted = isDeleted;
        this.systemDatetime = systemDatetime;
        this.DRecordStartdate = DRecordStartdate;
        this.DRecordEnddate = DRecordEnddate;
    }
    public UserMaster(String username, String password, String firstName, String lastName, String emailid, double mobileNo, int guid, int roleId, int templeMasterId, int makerId, int isDeleted, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate, Set userInfos, Set userAddressInfos) {
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.emailid = emailid;
       this.mobileNo = mobileNo;
       this.guid = guid;
       this.roleId = roleId;
       this.templeMasterId = templeMasterId;
       this.makerId = makerId;
       this.isDeleted = isDeleted;
       this.systemDatetime = systemDatetime;
       this.DRecordStartdate = DRecordStartdate;
       this.DRecordEnddate = DRecordEnddate;
       this.userInfos = userInfos;
       this.userAddressInfos = userAddressInfos;
    }
   
    public Integer getUserMasterId() {
        return this.userMasterId;
    }
    
    public void setUserMasterId(Integer userMasterId) {
        this.userMasterId = userMasterId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public double getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(double mobileNo) {
        this.mobileNo = mobileNo;
    }
    public int getGuid() {
        return this.guid;
    }
    
    public void setGuid(int guid) {
        this.guid = guid;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public int getTempleMasterId() {
        return this.templeMasterId;
    }
    
    public void setTempleMasterId(int templeMasterId) {
        this.templeMasterId = templeMasterId;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartdate() {
        return this.DRecordStartdate;
    }
    
    public void setDRecordStartdate(Date DRecordStartdate) {
        this.DRecordStartdate = DRecordStartdate;
    }
    public Date getDRecordEnddate() {
        return this.DRecordEnddate;
    }
    
    public void setDRecordEnddate(Date DRecordEnddate) {
        this.DRecordEnddate = DRecordEnddate;
    }
    public Set getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set userInfos) {
        this.userInfos = userInfos;
    }
    public Set getUserAddressInfos() {
        return this.userAddressInfos;
    }
    
    public void setUserAddressInfos(Set userAddressInfos) {
        this.userAddressInfos = userAddressInfos;
    }




}


