package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UserAddressInfo generated by hbm2java
 */
public class UserAddressInfo  implements java.io.Serializable {


     private Integer userInfoAddressId;
     private UserMaster userMaster;
     private String address;
     private int countryId;
     private int stateId;
     private int cityId;
     private int areaId;
     private double pincode;
     private int makerId;
     private Date systemDatetime;
     private Date DRecordStartdate;
     private Date DRecordEnddate;

    public UserAddressInfo() {
    }

    public UserAddressInfo(UserMaster userMaster, String address, int countryId, int stateId, int cityId, int areaId, double pincode, int makerId, Date systemDatetime, Date DRecordStartdate, Date DRecordEnddate) {
       this.userMaster = userMaster;
       this.address = address;
       this.countryId = countryId;
       this.stateId = stateId;
       this.cityId = cityId;
       this.areaId = areaId;
       this.pincode = pincode;
       this.makerId = makerId;
       this.systemDatetime = systemDatetime;
       this.DRecordStartdate = DRecordStartdate;
       this.DRecordEnddate = DRecordEnddate;
    }
   
    public Integer getUserInfoAddressId() {
        return this.userInfoAddressId;
    }
    
    public void setUserInfoAddressId(Integer userInfoAddressId) {
        this.userInfoAddressId = userInfoAddressId;
    }
    public UserMaster getUserMaster() {
        return this.userMaster;
    }
    
    public void setUserMaster(UserMaster userMaster) {
        this.userMaster = userMaster;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }
    public int getStateId() {
        return this.stateId;
    }
    
    public void setStateId(int stateId) {
        this.stateId = stateId;
    }
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public int getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }
    public double getPincode() {
        return this.pincode;
    }
    
    public void setPincode(double pincode) {
        this.pincode = pincode;
    }
    public int getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(int makerId) {
        this.makerId = makerId;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartdate() {
        return this.DRecordStartdate;
    }
    
    public void setDRecordStartdate(Date DRecordStartdate) {
        this.DRecordStartdate = DRecordStartdate;
    }
    public Date getDRecordEnddate() {
        return this.DRecordEnddate;
    }
    
    public void setDRecordEnddate(Date DRecordEnddate) {
        this.DRecordEnddate = DRecordEnddate;
    }




}


