package com.vdtltest;
// Generated 8 Oct, 2014 11:47:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * YearMaster generated by hbm2java
 */
public class YearMaster  implements java.io.Serializable {


     private Integer yearId;
     private String startDate;
     private String endDate;
     private String gujaratiYear;
     private int isDeleted;
     private Date systemDatetime;
     private Date DRecordStartDate;
     private Date DRecordEndDate;

    public YearMaster() {
    }

    public YearMaster(String startDate, String endDate, String gujaratiYear, int isDeleted, Date systemDatetime, Date DRecordStartDate, Date DRecordEndDate) {
       this.startDate = startDate;
       this.endDate = endDate;
       this.gujaratiYear = gujaratiYear;
       this.isDeleted = isDeleted;
       this.systemDatetime = systemDatetime;
       this.DRecordStartDate = DRecordStartDate;
       this.DRecordEndDate = DRecordEndDate;
    }
   
    public Integer getYearId() {
        return this.yearId;
    }
    
    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public String getGujaratiYear() {
        return this.gujaratiYear;
    }
    
    public void setGujaratiYear(String gujaratiYear) {
        this.gujaratiYear = gujaratiYear;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Date getSystemDatetime() {
        return this.systemDatetime;
    }
    
    public void setSystemDatetime(Date systemDatetime) {
        this.systemDatetime = systemDatetime;
    }
    public Date getDRecordStartDate() {
        return this.DRecordStartDate;
    }
    
    public void setDRecordStartDate(Date DRecordStartDate) {
        this.DRecordStartDate = DRecordStartDate;
    }
    public Date getDRecordEndDate() {
        return this.DRecordEndDate;
    }
    
    public void setDRecordEndDate(Date DRecordEndDate) {
        this.DRecordEndDate = DRecordEndDate;
    }




}


