package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0



/**
 * Tbladmin generated by hbm2java
 */
public class Tbladmin  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private String email;
     private String password;
     private String mobile;
     private int attempt;
     private String secque;
     private String secans;

    public Tbladmin() {
    }

	
    public Tbladmin(String firstname, String lastname, String email, String password, int attempt, String secque, String secans) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.password = password;
        this.attempt = attempt;
        this.secque = secque;
        this.secans = secans;
    }
    public Tbladmin(String firstname, String lastname, String email, String password, String mobile, int attempt, String secque, String secans) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.password = password;
       this.mobile = mobile;
       this.attempt = attempt;
       this.secque = secque;
       this.secans = secans;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public int getAttempt() {
        return this.attempt;
    }
    
    public void setAttempt(int attempt) {
        this.attempt = attempt;
    }
    public String getSecque() {
        return this.secque;
    }
    
    public void setSecque(String secque) {
        this.secque = secque;
    }
    public String getSecans() {
        return this.secans;
    }
    
    public void setSecans(String secans) {
        this.secans = secans;
    }




}


