package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tblarea generated by hbm2java
 */
public class Tblarea  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer enable;
     private Set tbldonors = new HashSet(0);

    public Tblarea() {
    }

	
    public Tblarea(String name) {
        this.name = name;
    }
    public Tblarea(String name, Integer enable, Set tbldonors) {
       this.name = name;
       this.enable = enable;
       this.tbldonors = tbldonors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getEnable() {
        return this.enable;
    }
    
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
    public Set getTbldonors() {
        return this.tbldonors;
    }
    
    public void setTbldonors(Set tbldonors) {
        this.tbldonors = tbldonors;
    }




}


