package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tblaccount generated by hbm2java
 */
public class Tblaccount  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int enable;
     private Set tbldonationdetails = new HashSet(0);

    public Tblaccount() {
    }

	
    public Tblaccount(String name, int enable) {
        this.name = name;
        this.enable = enable;
    }
    public Tblaccount(String name, int enable, Set tbldonationdetails) {
       this.name = name;
       this.enable = enable;
       this.tbldonationdetails = tbldonationdetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getEnable() {
        return this.enable;
    }
    
    public void setEnable(int enable) {
        this.enable = enable;
    }
    public Set getTbldonationdetails() {
        return this.tbldonationdetails;
    }
    
    public void setTbldonationdetails(Set tbldonationdetails) {
        this.tbldonationdetails = tbldonationdetails;
    }




}


