package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tblcity generated by hbm2java
 */
public class Tblcity  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set tbldonors = new HashSet(0);

    public Tblcity() {
    }

	
    public Tblcity(String name) {
        this.name = name;
    }
    public Tblcity(String name, Set tbldonors) {
       this.name = name;
       this.tbldonors = tbldonors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTbldonors() {
        return this.tbldonors;
    }
    
    public void setTbldonors(Set tbldonors) {
        this.tbldonors = tbldonors;
    }




}


