package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tbldonationdetail generated by hbm2java
 */
public class Tbldonationdetail  implements java.io.Serializable {


     private Integer id;
     private Tbldonor tbldonor;
     private Tblproduct tblproduct;
     private Tblaccount tblaccount;
     private Tbluser tbluser;
     private String receiptno;
     private int amount;
     private int qty;
     private Date date;

    public Tbldonationdetail() {
    }

    public Tbldonationdetail(Tbldonor tbldonor, Tblproduct tblproduct, Tblaccount tblaccount, Tbluser tbluser, String receiptno, int amount, int qty, Date date) {
       this.tbldonor = tbldonor;
       this.tblproduct = tblproduct;
       this.tblaccount = tblaccount;
       this.tbluser = tbluser;
       this.receiptno = receiptno;
       this.amount = amount;
       this.qty = qty;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tbldonor getTbldonor() {
        return this.tbldonor;
    }
    
    public void setTbldonor(Tbldonor tbldonor) {
        this.tbldonor = tbldonor;
    }
    public Tblproduct getTblproduct() {
        return this.tblproduct;
    }
    
    public void setTblproduct(Tblproduct tblproduct) {
        this.tblproduct = tblproduct;
    }
    public Tblaccount getTblaccount() {
        return this.tblaccount;
    }
    
    public void setTblaccount(Tblaccount tblaccount) {
        this.tblaccount = tblaccount;
    }
    public Tbluser getTbluser() {
        return this.tbluser;
    }
    
    public void setTbluser(Tbluser tbluser) {
        this.tbluser = tbluser;
    }
    public String getReceiptno() {
        return this.receiptno;
    }
    
    public void setReceiptno(String receiptno) {
        this.receiptno = receiptno;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


