package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tbldonor generated by hbm2java
 */
public class Tbldonor  implements java.io.Serializable {


     private Integer id;
     private Tblarea tblarea;
     private Tblcity tblcity;
     private String serial;
     private String firstname;
     private String lastname;
     private String mobile;
     private String email;
     private String address;
     private Set tbldonationdetails = new HashSet(0);
     private Set tblspnotes = new HashSet(0);

    public Tbldonor() {
    }

	
    public Tbldonor(Tblarea tblarea, Tblcity tblcity, String serial, String firstname, String lastname, String mobile, String email, String address) {
        this.tblarea = tblarea;
        this.tblcity = tblcity;
        this.serial = serial;
        this.firstname = firstname;
        this.lastname = lastname;
        this.mobile = mobile;
        this.email = email;
        this.address = address;
    }
    public Tbldonor(Tblarea tblarea, Tblcity tblcity, String serial, String firstname, String lastname, String mobile, String email, String address, Set tbldonationdetails, Set tblspnotes) {
       this.tblarea = tblarea;
       this.tblcity = tblcity;
       this.serial = serial;
       this.firstname = firstname;
       this.lastname = lastname;
       this.mobile = mobile;
       this.email = email;
       this.address = address;
       this.tbldonationdetails = tbldonationdetails;
       this.tblspnotes = tblspnotes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tblarea getTblarea() {
        return this.tblarea;
    }
    
    public void setTblarea(Tblarea tblarea) {
        this.tblarea = tblarea;
    }
    public Tblcity getTblcity() {
        return this.tblcity;
    }
    
    public void setTblcity(Tblcity tblcity) {
        this.tblcity = tblcity;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getTbldonationdetails() {
        return this.tbldonationdetails;
    }
    
    public void setTbldonationdetails(Set tbldonationdetails) {
        this.tbldonationdetails = tbldonationdetails;
    }
    public Set getTblspnotes() {
        return this.tblspnotes;
    }
    
    public void setTblspnotes(Set tblspnotes) {
        this.tblspnotes = tblspnotes;
    }




}


