package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0



/**
 * Tblproductdetail generated by hbm2java
 */
public class Tblproductdetail  implements java.io.Serializable {


     private Integer id;
     private Tblproduct tblproduct;
     private int minrs;
     private int maxrs;
     private int maxqty;

    public Tblproductdetail() {
    }

    public Tblproductdetail(Tblproduct tblproduct, int minrs, int maxrs, int maxqty) {
       this.tblproduct = tblproduct;
       this.minrs = minrs;
       this.maxrs = maxrs;
       this.maxqty = maxqty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tblproduct getTblproduct() {
        return this.tblproduct;
    }
    
    public void setTblproduct(Tblproduct tblproduct) {
        this.tblproduct = tblproduct;
    }
    public int getMinrs() {
        return this.minrs;
    }
    
    public void setMinrs(int minrs) {
        this.minrs = minrs;
    }
    public int getMaxrs() {
        return this.maxrs;
    }
    
    public void setMaxrs(int maxrs) {
        this.maxrs = maxrs;
    }
    public int getMaxqty() {
        return this.maxqty;
    }
    
    public void setMaxqty(int maxqty) {
        this.maxqty = maxqty;
    }




}


