package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tblspnote generated by hbm2java
 */
public class Tblspnote  implements java.io.Serializable {


     private Integer id;
     private Tbldonor tbldonor;
     private Date date;
     private String note;

    public Tblspnote() {
    }

    public Tblspnote(Tbldonor tbldonor, Date date, String note) {
       this.tbldonor = tbldonor;
       this.date = date;
       this.note = note;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tbldonor getTbldonor() {
        return this.tbldonor;
    }
    
    public void setTbldonor(Tbldonor tbldonor) {
        this.tbldonor = tbldonor;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


