package com.beans;
// Generated 7 Oct, 2014 9:57:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tbluser generated by hbm2java
 */
public class Tbluser  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private String email;
     private String mobile;
     private String address;
     private String imgpath;
     private String password;
     private boolean enable;
     private Set tbldonationdetails = new HashSet(0);

    public Tbluser() {
    }

	
    public Tbluser(String firstname, String lastname, String email, String mobile, String address, String imgpath, String password, boolean enable) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.mobile = mobile;
        this.address = address;
        this.imgpath = imgpath;
        this.password = password;
        this.enable = enable;
    }
    public Tbluser(String firstname, String lastname, String email, String mobile, String address, String imgpath, String password, boolean enable, Set tbldonationdetails) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.mobile = mobile;
       this.address = address;
       this.imgpath = imgpath;
       this.password = password;
       this.enable = enable;
       this.tbldonationdetails = tbldonationdetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getImgpath() {
        return this.imgpath;
    }
    
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEnable() {
        return this.enable;
    }
    
    public void setEnable(boolean enable) {
        this.enable = enable;
    }
    public Set getTbldonationdetails() {
        return this.tbldonationdetails;
    }
    
    public void setTbldonationdetails(Set tbldonationdetails) {
        this.tbldonationdetails = tbldonationdetails;
    }




}


